package usbharu.genshintools.shield;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;

public class CharacterShieldCal {
	public JPanel contenPane;
	private JComboBox characterSelect;
	private JPanel characterCard;
	private JPanel diona;
	private JFormattedTextField hpInput;
	private JLabel name;
	private JLabel hpLabel;
	private JFormattedTextField talentsInput;
	private JLabel talentsLabel;
	private JLabel c2Label;
	private JLabel holdLabel;
	private JTextField textField3;
	private JTextField textField4;
	private JTextField textField5;
	private JTextField textField6;
	private JTextField textField7;
	private JFormattedTextField shieldIncreasesInput;

	private ResourceBundle resourceBundle = null;

	public CharacterShieldCal() {
		hpInput.addActionListener(new ActionListener() {
			/**
			 * Invoked when an action occurs.
			 *
			 * @param e the event to be processed
			 */
			@Override
			public void actionPerformed(ActionEvent e) {
				if (characterSelect.getSelectedItem() == null) {
					return;
				}
				ShieldCal.shieldStrength(resourceBundle, (int) hpInput.getValue(), (int) talentsInput.getValue(), (int) shieldIncreasesInput.getValue());
			}
		});
		talentsInput.addActionListener(new ActionListener() {
			/**
			 * Invoked when an action occurs.
			 *
			 * @param e the event to be processed
			 */
			@Override
			public void actionPerformed(ActionEvent e) {

			}
		});
		shieldIncreasesInput.addActionListener(new ActionListener() {
			/**
			 * Invoked when an action occurs.
			 *
			 * @param e the event to be processed
			 */
			@Override
			public void actionPerformed(ActionEvent e) {

			}
		});
		characterSelect.addActionListener(new ActionListener() {
			/**
			 * Invoked when an action occurs.
			 *
			 * @param e the event to be processed
			 */
			@Override
			public void actionPerformed(ActionEvent e) {
				if (characterSelect.getSelectedItem() == null) {
					return;
				}
				resourceBundle = ResourceBundle.getBundle((String) characterSelect.getSelectedItem());
			}
		});
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		contenPane = new JPanel();
		contenPane.setLayout(new BorderLayout(0, 0));
		characterCard = new JPanel();
		characterCard.setLayout(new CardLayout(0, 0));
		contenPane.add(characterCard, BorderLayout.CENTER);
		diona = new JPanel();
		diona.setLayout(new GridBagLayout());
		characterCard.add(diona, "diona");
		name = new JLabel();
		name.setText("diona");
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		diona.add(name, gbc);
		hpInput = new JFormattedTextField();
		hpInput.setText("0");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		diona.add(hpInput, gbc);
		hpLabel = new JLabel();
		hpLabel.setText("HP");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		diona.add(hpLabel, gbc);
		talentsInput = new JFormattedTextField();
		talentsInput.setText("1");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		diona.add(talentsInput, gbc);
		talentsLabel = new JLabel();
		talentsLabel.setText("Talents");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		diona.add(talentsLabel, gbc);
		textField3 = new JTextField();
		textField3.setEditable(false);
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		diona.add(textField3, gbc);
		final JLabel label1 = new JLabel();
		label1.setText("Base Shield");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		diona.add(label1, gbc);
		textField4 = new JTextField();
		textField4.setEditable(false);
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		diona.add(textField4, gbc);
		final JLabel label2 = new JLabel();
		label2.setText("Total Shield");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		diona.add(label2, gbc);
		c2Label = new JLabel();
		c2Label.setText("C2");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 3;
		gbc.anchor = GridBagConstraints.WEST;
		diona.add(c2Label, gbc);
		holdLabel = new JLabel();
		holdLabel.setText("hold");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 4;
		gbc.anchor = GridBagConstraints.WEST;
		diona.add(holdLabel, gbc);
		textField5 = new JTextField();
		textField5.setEditable(false);
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 3;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		diona.add(textField5, gbc);
		textField6 = new JTextField();
		textField6.setEditable(false);
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 4;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		diona.add(textField6, gbc);
		final JLabel label3 = new JLabel();
		label3.setText("Cyro DMG");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 5;
		gbc.anchor = GridBagConstraints.WEST;
		diona.add(label3, gbc);
		textField7 = new JTextField();
		textField7.setEditable(false);
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 5;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		diona.add(textField7, gbc);
		shieldIncreasesInput = new JFormattedTextField();
		shieldIncreasesInput.setText("0");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 3;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		diona.add(shieldIncreasesInput, gbc);
		final JLabel label4 = new JLabel();
		label4.setText("Shield Increases");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.anchor = GridBagConstraints.WEST;
		diona.add(label4, gbc);
		characterSelect = new JComboBox();
		contenPane.add(characterSelect, BorderLayout.NORTH);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contenPane;
	}

	public void setShieldCal() {

	}

}