package usbharu.resincal;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.NumberFormat;

/**
 * 樹脂の数と時間を計算するguiのコントローラー
 *
 * @author usbharu
 * @version 1.0.0
 * @since 1.0.0
 */
public class ResinCounter {
	JPanel contentPane;
	private JFormattedTextField resinInput;
	private JFormattedTextField timeInput;
	private JLabel resin;
	private JLabel time;
	private JLabel allow;

	public ResinCounter() {
		$$$setupUI$$$();
		resinInput.addActionListener(new ActionListener() {
			/**
			 * Invoked when an action occurs.
			 *
			 * @param e the event to be processed
			 */
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					timeInput.setText(String.valueOf(ResinCalculate.convertIntoTime(Integer.parseInt(resinInput.getText()))));
				} catch (NumberFormatException numberFormatException) {
					numberFormatException.printStackTrace();
				}
			}
		});
		timeInput.addActionListener(new ActionListener() {
			/**
			 * Invoked when an action occurs.
			 *
			 * @param e the event to be processed
			 */
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					resinInput.setText(String.valueOf(ResinCalculate.convertIntoResin(Integer.parseInt(timeInput.getText()))));
				} catch (NumberFormatException numberFormatException) {
					numberFormatException.printStackTrace();
				}
			}
		});
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		contentPane = new JPanel();
		contentPane.setLayout(new BorderLayout(0, 0));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridBagLayout());
		contentPane.add(panel1, BorderLayout.CENTER);
		allow = new JLabel();
		allow.setText("↔");
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.weighty = 1.0;
		panel1.add(allow, gbc);
		resinInput.setColumns(10);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel1.add(resinInput, gbc);
		timeInput.setColumns(10);
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 1;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel1.add(timeInput, gbc);
		resin = new JLabel();
		resin.setText("Resin・樹脂");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		panel1.add(resin, gbc);
		time = new JLabel();
		time.setText("Time(minute)・時間(分)");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		panel1.add(time, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contentPane;
	}

	private void createUIComponents() {
		resinInput = new JFormattedTextField(NumberFormat.getNumberInstance());
		timeInput = new JFormattedTextField(NumberFormat.getNumberInstance());
	}
}