package usbharu.genshintools.shield;

import usbharu.genshintools.gui.IContentPane;
import usbharu.genshintools.main.Main;
import usbharu.genshintools.shield.character.Diona;
import usbharu.genshintools.shield.character.Noelle;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class CharacterShieldCal implements IContentPane {
	public DefaultComboBoxModel<IContentPane> model;
	private JComboBox<IContentPane> characterSelect;
	private JPanel contentPane;
	private JButton backButton;
	private JPanel toolPanel;

	public CharacterShieldCal() {
		$$$setupUI$$$();
		if (characterSelect.getSelectedItem() == null) {
			return;
		}
		contentPane.add(((IContentPane) model.getSelectedItem()).getContentPane(), BorderLayout.CENTER);
		characterSelect.addActionListener(new ActionListener() {
			/**
			 * Invoked when an action occurs.
			 *
			 * @param e the event to be processed
			 */
			@Override
			public void actionPerformed(ActionEvent e) {
				if (characterSelect.getSelectedItem() == null) {
					return;
				}
				contentPane.removeAll();
				toolPanel.add(backButton, BorderLayout.WEST);
				toolPanel.add(characterSelect, BorderLayout.CENTER);
				contentPane.add(toolPanel, BorderLayout.NORTH);
				contentPane.add(((IContentPane) characterSelect.getSelectedItem()).getContentPane(), BorderLayout.CENTER);
				contentPane.repaint();
				contentPane.revalidate();
			}
		});
		backButton.addActionListener(new ActionListener() {
			/**
			 * Invoked when an action occurs.
			 *
			 * @param e the event to be processed
			 */
			@Override
			public void actionPerformed(ActionEvent e) {
				Main.main();
			}
		});
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		contentPane = new JPanel();
		contentPane.setLayout(new BorderLayout(0, 0));
		toolPanel = new JPanel();
		toolPanel.setLayout(new BorderLayout(0, 0));
		contentPane.add(toolPanel, BorderLayout.NORTH);
		toolPanel.add(characterSelect, BorderLayout.CENTER);
		backButton = new JButton();
		backButton.setText("back");
		toolPanel.add(backButton, BorderLayout.WEST);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contentPane;
	}

	private void createUIComponents() {
		model = new DefaultComboBoxModel<>();
		model.addElement(new Diona());
		model.addElement(new Noelle());
		characterSelect = new JComboBox<>(model);
	}

	public JPanel getContentPane() {
		return contentPane;
	}

	@Override
	public String getName() {
		return "Shield";
	}
}